apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-module-gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-module-gitlab
  template:
    metadata: 
      labels:
        app: consumer-module-gitlab
    spec:
      containers:
      - name: consumer-module-gitlab-container
        image: "ulriksandberg/consumer:2.6"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-module-gitlab-service
spec:
  selector:
    app: consumer-module-gitlab
  ports:
  - port: 7070
    targetPort: 80
  type: LoadBalancer